INSERT INTO regioni VALUES
    ('Veneto'),
    ('Campania'),
    ('Abruzzo'),
    ('Piemonte'),
    ('Lombardia'),
    ('Toscana'),
    ('Marche'),
    ('Sardegna'),
    ('Emilia-Romagna'),
    ('Lazio'),
    ('Umbria'),
    ('Basilicata'),
    ('Trentino-Alto Adige'),
    ('Sicilia'),
    ('Puglia'),
    ('Calabria'),
    ('Liguria'),
    ('Molise'),
    ('Friuli-Venezia Giulia'),
    ('Valle d''Aosta');
